name: inference
channels:
  - defaults
  - conda-forge
dependencies:
  - databricks-sdk=0.28.0
  - fastapi=0.103.0
  - mlflow=2.12.2
  - python=3.10
  - python-dotenv=0.21.0
  - pytorch=2.3.1
  - scikit-learn=1.4.2
  - transformers=4.41.2
  - uvicorn=0.20.0
