input_data_path: 'data/preprocessed/amz_products_small_bert_tiny_encoded_v2.parquet'
input_data_encoded: True
data_load: 'memory'
trainable_layers: 3
bert_model_name: "prajjwal1/bert-tiny"
num_epochs: 3
batch_size: 32
test_batch_size: 32
learning_rate: 1e-5
optimizer: 'AdamW'
device: 'cuda'
seed: 42
data_fraction: 1.0
