input_data_path: 'data/preprocessed/amz_products_small_preprocessed_v1.parquet'
bert_model_name: "prajjwal1/bert-tiny"
num_epochs: 3
batch_size: 64
test_batch_size: 64
learning_rate: 1e-6
optimizer: "AdamW"
device: "cuda"
seed: 42
data_fraction: 1.0