name: training
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - databricks-sdk=0.28.0
  - fire=0.6.0
  - mlflow=2.12.2
  - pandas=2.2.2
  - pyspark=3.4.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch::pytorch=2.3.1
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch-mutex=1.0
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - pytorch::torchtriton=2.3.1
  - tqdm=4.66.4
  - transformers=4.41.2
  - yaml=0.2.5


